spring:
  neo4j:
    uri: ${OCM_NEO4J_DB_URI:bolt://localhost:7687}
    authentication:
      username: ${OCM_NEO4J_DB_USERNAME}
      password: ${OCM_NEO4J_DB_PASSWORD}
  webflux:
    multipart:
      max-headers-size: ${OCM_MULTI_PART_MAX_HEADER_SIZE:15MB}
  main:
    banner-mode: off
  web:
    resources:
      static-locations: "classpath:oc-manager-ui/"

server:
  http2:
    enabled: true

oc:
  configuration:
    data-dir: ${OCM_DATA_DIR:./ocm-data}
    thumbnail-size: ${OCM_THUMBNAIL_SIZE:300}
    thumbnail-type: ${OCM_THUMBNAIL_TYPE:jpg}
