spring:
  neo4j:
    uri: "bolt://localhost:47620" # Default port 7687
    authentication:
      username: "neo4j"
      password: "ocManager"
  webflux:
    multipart:
      max-headers-size: ${OCM_MULTI_PART_MAX_HEADER_SIZE:15MB}
  main:
    banner-mode: off
  web:
    resources:
      static-locations: "classpath:oc-manager-ui/"

server:
  http2:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: shutdown
      cors:
        allowed-origin-patterns: "http://localhost:[*]"
        allowed-methods: "POST"
        allowed-headers: "*"
  endpoint:
    shutdown:
      enabled: true

oc:
  configuration:
    data-dir: ${OCM_DATA_DIR:./ocm-data}
    thumbnail-size: ${OCM_THUMBNAIL_SIZE:300}
    thumbnail-type: ${OCM_THUMBNAIL_TYPE:jpg}
