spring:
  neo4j:
    authentication:
      username: "neo4j"
      password: "password"

logging:
  level:
    nl.juraji: debug
    org.springframework.web: debug
    org.springframework.context.support: debug
    org.springframework.data.neo4j: debug
